// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emlfypsnbxfjhhqcqfni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbGZ5cHNuYnhmamhocWNxZm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjczNzksImV4cCI6MjA2Mzc0MzM3OX0.S74tJ_ylFwT90JEshD6mf21eRjod16hPXyMc6wjreJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);